/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProcessosRouteImport } from './routes/processos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PatioRouteImport } from './routes/patio'
import { Route as ObjetosRouteImport } from './routes/objetos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaudosRouteImport } from './routes/laudos'
import { Route as DestruicaoRouteImport } from './routes/destruicao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CobrancasRouteImport } from './routes/cobrancas'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VeiculosIdRouteImport } from './routes/veiculos.$id'
import { Route as ObjetosIdRouteImport } from './routes/objetos.$id'
import { Route as ApiPlateLookupRouteImport } from './routes/api/plate-lookup'

const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosRoute = ProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PatioRoute = PatioRouteImport.update({
  id: '/patio',
  path: '/patio',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetosRoute = ObjetosRouteImport.update({
  id: '/objetos',
  path: '/objetos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaudosRoute = LaudosRouteImport.update({
  id: '/laudos',
  path: '/laudos',
  getParentRoute: () => rootRouteImport,
} as any)
const DestruicaoRoute = DestruicaoRouteImport.update({
  id: '/destruicao',
  path: '/destruicao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancasRoute = CobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosIdRoute = VeiculosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VeiculosRoute,
} as any)
const ObjetosIdRoute = ObjetosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ObjetosRoute,
} as any)
const ApiPlateLookupRoute = ApiPlateLookupRouteImport.update({
  id: '/api/plate-lookup',
  path: '/api/plate-lookup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/checklist': typeof ChecklistRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/destruicao': typeof DestruicaoRoute
  '/laudos': typeof LaudosRoute
  '/login': typeof LoginRoute
  '/objetos': typeof ObjetosRouteWithChildren
  '/patio': typeof PatioRoute
  '/perfil': typeof PerfilRoute
  '/processos': typeof ProcessosRoute
  '/relatorios': typeof RelatoriosRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRouteWithChildren
  '/api/plate-lookup': typeof ApiPlateLookupRoute
  '/objetos/$id': typeof ObjetosIdRoute
  '/veiculos/$id': typeof VeiculosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/checklist': typeof ChecklistRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/destruicao': typeof DestruicaoRoute
  '/laudos': typeof LaudosRoute
  '/login': typeof LoginRoute
  '/objetos': typeof ObjetosRouteWithChildren
  '/patio': typeof PatioRoute
  '/perfil': typeof PerfilRoute
  '/processos': typeof ProcessosRoute
  '/relatorios': typeof RelatoriosRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRouteWithChildren
  '/api/plate-lookup': typeof ApiPlateLookupRoute
  '/objetos/$id': typeof ObjetosIdRoute
  '/veiculos/$id': typeof VeiculosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/checklist': typeof ChecklistRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/destruicao': typeof DestruicaoRoute
  '/laudos': typeof LaudosRoute
  '/login': typeof LoginRoute
  '/objetos': typeof ObjetosRouteWithChildren
  '/patio': typeof PatioRoute
  '/perfil': typeof PerfilRoute
  '/processos': typeof ProcessosRoute
  '/relatorios': typeof RelatoriosRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRouteWithChildren
  '/api/plate-lookup': typeof ApiPlateLookupRoute
  '/objetos/$id': typeof ObjetosIdRoute
  '/veiculos/$id': typeof VeiculosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/checklist'
    | '/cobrancas'
    | '/configuracoes'
    | '/destruicao'
    | '/laudos'
    | '/login'
    | '/objetos'
    | '/patio'
    | '/perfil'
    | '/processos'
    | '/relatorios'
    | '/unidades'
    | '/usuarios'
    | '/veiculos'
    | '/api/plate-lookup'
    | '/objetos/$id'
    | '/veiculos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/checklist'
    | '/cobrancas'
    | '/configuracoes'
    | '/destruicao'
    | '/laudos'
    | '/login'
    | '/objetos'
    | '/patio'
    | '/perfil'
    | '/processos'
    | '/relatorios'
    | '/unidades'
    | '/usuarios'
    | '/veiculos'
    | '/api/plate-lookup'
    | '/objetos/$id'
    | '/veiculos/$id'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/checklist'
    | '/cobrancas'
    | '/configuracoes'
    | '/destruicao'
    | '/laudos'
    | '/login'
    | '/objetos'
    | '/patio'
    | '/perfil'
    | '/processos'
    | '/relatorios'
    | '/unidades'
    | '/usuarios'
    | '/veiculos'
    | '/api/plate-lookup'
    | '/objetos/$id'
    | '/veiculos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  ChecklistRoute: typeof ChecklistRoute
  CobrancasRoute: typeof CobrancasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DestruicaoRoute: typeof DestruicaoRoute
  LaudosRoute: typeof LaudosRoute
  LoginRoute: typeof LoginRoute
  ObjetosRoute: typeof ObjetosRouteWithChildren
  PatioRoute: typeof PatioRoute
  PerfilRoute: typeof PerfilRoute
  ProcessosRoute: typeof ProcessosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  UnidadesRoute: typeof UnidadesRoute
  UsuariosRoute: typeof UsuariosRoute
  VeiculosRoute: typeof VeiculosRouteWithChildren
  ApiPlateLookupRoute: typeof ApiPlateLookupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos': {
      id: '/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patio': {
      id: '/patio'
      path: '/patio'
      fullPath: '/patio'
      preLoaderRoute: typeof PatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetos': {
      id: '/objetos'
      path: '/objetos'
      fullPath: '/objetos'
      preLoaderRoute: typeof ObjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laudos': {
      id: '/laudos'
      path: '/laudos'
      fullPath: '/laudos'
      preLoaderRoute: typeof LaudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destruicao': {
      id: '/destruicao'
      path: '/destruicao'
      fullPath: '/destruicao'
      preLoaderRoute: typeof DestruicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobrancas': {
      id: '/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof CobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos/$id': {
      id: '/veiculos/$id'
      path: '/$id'
      fullPath: '/veiculos/$id'
      preLoaderRoute: typeof VeiculosIdRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/objetos/$id': {
      id: '/objetos/$id'
      path: '/$id'
      fullPath: '/objetos/$id'
      preLoaderRoute: typeof ObjetosIdRouteImport
      parentRoute: typeof ObjetosRoute
    }
    '/api/plate-lookup': {
      id: '/api/plate-lookup'
      path: '/api/plate-lookup'
      fullPath: '/api/plate-lookup'
      preLoaderRoute: typeof ApiPlateLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ObjetosRouteChildren {
  ObjetosIdRoute: typeof ObjetosIdRoute
}

const ObjetosRouteChildren: ObjetosRouteChildren = {
  ObjetosIdRoute: ObjetosIdRoute,
}

const ObjetosRouteWithChildren =
  ObjetosRoute._addFileChildren(ObjetosRouteChildren)

interface VeiculosRouteChildren {
  VeiculosIdRoute: typeof VeiculosIdRoute
}

const VeiculosRouteChildren: VeiculosRouteChildren = {
  VeiculosIdRoute: VeiculosIdRoute,
}

const VeiculosRouteWithChildren = VeiculosRoute._addFileChildren(
  VeiculosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  ChecklistRoute: ChecklistRoute,
  CobrancasRoute: CobrancasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DestruicaoRoute: DestruicaoRoute,
  LaudosRoute: LaudosRoute,
  LoginRoute: LoginRoute,
  ObjetosRoute: ObjetosRouteWithChildren,
  PatioRoute: PatioRoute,
  PerfilRoute: PerfilRoute,
  ProcessosRoute: ProcessosRoute,
  RelatoriosRoute: RelatoriosRoute,
  UnidadesRoute: UnidadesRoute,
  UsuariosRoute: UsuariosRoute,
  VeiculosRoute: VeiculosRouteWithChildren,
  ApiPlateLookupRoute: ApiPlateLookupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
